config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'home#index'

  resources :comments
  resources :posts, except: [:index] do
    resource :comments, shallow: true
  end

  resource :tags do
    member do
      get 'posts'
    end
  end

  get '/users/:id', to: 'users#show', as: :user
  get 'dashboard', to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :user

  has_rich_text :content
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[edit show update destroy ]
  before_action :set_post, except: [:index]
  before_action :authenticate_user!

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # Gets all comments. From post nested resource
  def show
    # GET /posts/1/comments/
    if @post.present?
      @comments = @post.comments.includes(:user).with_rich_text_content
    end
  end

  # New comment. From post nested resource
  def new
    # GET /posts/1/comments/new
    if @post.present?
      @comment = Comment.new
      @comment.post = @post
    end
  end

  # GET /comments/1/edit
  # Edit comment. From post nested resource
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(comment_params)
    @comment.post = @post
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        @post.comments << @comment
        format.html { redirect_to post_path(@post.permalink), notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@post.permalink), notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@post.permalink), notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.slim
= simple_form_for(@comment) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.association :post
    = f.association :user

  .form-actions
    = f.button :submit

app/views/comments/edit.html.slim
h1 Editing comment

== render 'form'

=> link_to 'Show', @comment
'|
=< link_to 'Back', comments_path

app/views/comments/index.html.slim
h1 Listing comments

table
  thead
    tr
      th Post
      th User
      th
      th
      th

  tbody
    - @comments.each do |comment|
      tr
        td = comment.post
        td = comment.user
        td = link_to 'Show', comment
        td = link_to 'Edit', edit_comment_path(comment)
        td = link_to 'Destroy', comment, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.slim
h1 New comment

== render 'form'

= link_to 'Back', comments_path

app/views/comments/show.html.slim
p#notice = notice
.container.is-fluid.comment
  p
    strong User:
    = @comment.user
  hr
  == @comment.content