config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'home#index'

  resources :comments
  resources :posts, except: [:index] do
    resource :comments, shallow: true
  end

  resource :tags do
    member do
      get 'posts'
    end
  end

  get '/users/:id', to: 'users#show', as: :user
  get 'dashboard', to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :posts
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: %i[edit update destroy]
  before_action :authenticate_user!, only: %i[edit update destroy]

  def posts
    @tag = Tag.find_by(permalink: search_params)
    @posts = @tag.posts.newest
    respond_to do |format|
      unless (@posts.nil? || @tag.nil?)
        format.html { render :index,
                      notice: "Posts tagged as #{ search_params }"}
      else
        format.html { render :not_found }
      end
    end
  end

  # GET /tags
  def show
  end

  def index
    @tags = Tag.all
  end

  # GET /tags/1/edit
  def edit
  end

  # PATCH/PUT /tags/1
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /tags/1
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url,
                    notice: 'Tag was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      # set tag by id or permalink
      if params[:id].is_a? Integer
        @tag = Tag.find(params[:id])
      else
        @tag = Tag.find_by(permalink: params[:id])
        raise ActiveRecord::RecordNotFound if @tag.nil?
      end
    end

    def tag_params
      params.require(:tag).permit(:name, :posts_id)
    end

    def search_params
      params.require(:tag)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.slim
= simple_form_for(@tag) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.association :posts

  .form-actions
    = f.button :submit

app/views/tags/_numbered_tags.html.slim
- if !@tags.nil?
  h1.subtitle Search by tag
  .tags.has-addons
    - @tags.each do |tag|
      - cache tag do
          div style='margin-right: 1rem;'
            a.tag.is-link href=posts_tags_path(tag: tag.permalink) #{tag.name}
            - current_user.present? && current_user.admin?
              span.tag.counter-tag #{tag.posts.count}
- elsif @tag.present?
  h1.subtitle Showing posts by:
  span.tag.is-primary #{@tag.name}

app/views/tags/_post_header.html.slim
scss:
  $claret: #990f3d;
  .listing-tag {
      background-color: inherit !important;
      color: $claret !important;
      font-weight: 600 !important;
      border: 2px solid $claret !important;
  }

- unless tags.nil?
  .tags
    - tags.each do |tag|
      a.tag.listing-tag.is-link href=posts_tags_path(tag: tag.permalink) #{tag.name}

app/views/tags/edit.html.slim
h1 Editing tag

== render 'form'

=> link_to 'Show', @tag
'|
=< link_to 'Back', tags_path

app/views/tags/index.html.slim
== render file: 'home/index'

app/views/tags/new.html.slim
h1 New tag

== render 'form'

= link_to 'Back', tags_path

app/views/tags/search.html.slim
== render 'layouts/posts_listing'

app/views/tags/show.html.slim
p#notice = notice

p
  strong Name:
  = @tag.name
p
  strong Posts:
  = @tag.posts

=> link_to 'Edit', edit_tag_path(@tag)
'|
=< link_to 'Back', tags_path