config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'
  devise_for :users
  root to: 'home#index'

  resources :comments
  resources :posts, except: [:index] do
    resource :comments, shallow: true
  end

  resource :tags do
    member do
      get 'posts'
    end
  end

  get '/users/:id', to: 'users#show', as: :user
  get 'dashboard', to: 'dashboard#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:avatar])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar(user, size=128)

    img_component =
      if (user) and (!user.avatar.nil?) and user.avatar.attached?
        tag(:img,
            'data-src' => polymorphic_url(user.avatar.variant(resize_to_fill: [size, size])),
            class: 'is-rounded lazyload', id: 'upload-image')
      else
        content_tag(:div, link_to('Upload Photo',
                                  edit_user_registration_path(user)),
                    class: 'img-placeholder container-hcenters')
      end
    content_tag(:figure,
                img_component,
                class: %W(image
                          form-avatar-img-area
                          container-hcenters
                          is-#{size}x#{size}),
                id: 'upload-image'
               )
  end

  # Not lazy
  def user_avatar_nl(user, size=128)

    img_component =
      if (user) and (!user.avatar.nil?) and user.avatar.attached?
        tag(:img,
            src: polymorphic_url(user.avatar.variant(resize_to_fill: [size, size])),
            class: 'is-rounded', id: 'upload-image')
      else
        content_tag(:div, link_to('Upload Photo',
                                  edit_user_registration_path(user)),
                    class: 'img-placeholder container-hcenters')
      end
    content_tag(:figure,
                img_component,
                class: %W(image
                          form-avatar-img-area
                          container-hcenters
                          is-#{size}x#{size}),
                id: 'upload-image'
               )
  end

  def render_tags(tags)
    unless tags.nil?
      tags_html = tags.map do |tag|
        content_tag(:a, tag.name, class:'tag is-link is-rounded',
                    href: search_by_tag_path(tag.permalink) )
      end.reduce(&:+)

      content_tag(:div,
                  tags_html,
                  class: 'tags')
    end
  end
end

app/views/application/_centered_form.html.slim
section.hero.is-primary.is-fullheight
  .hero-body
    .container
      .columns.is-centered
        .column.is-5-tablet.is-4-desktop.is-4-widescreen
          .box
            == yield

app/views/application/_footer.html.slim
.footer
  p Copyright &copy; 2020 Pedro Pinheiro. All rights reserved.

app/views/application/_global_navbar.html.slim
nav.navbar
  .container
    .navbar-brand
      span.is-size-3
        a.navbar-item href=root_path Dreams of Code
      a.navbar-burger.burger role='button' aria-label='menu' aria-expanded='false' data-target='navbarMenuHero'
        span aria-hidden='true'
        span aria-hidden='true'
        span aria-hidden='true'
    div.navbar-menu id='navbarMenuHero'
      .navbar-end
        a.navbar-item href=root_path Home
        - unless user_signed_in?
          a.navbar-item href=new_user_session_path Log in
        - else
          = link_to 'Log out', destroy_user_session_path(current_user), class: 'navbar-item', method: :delete
        a.navbar-item target='_blank' href='https://pmop.github.com' About me

app/views/application/_special_navbar.html.slim
nav.navbar role='navigation' aria-label='main navigation'
    .navbar_start
      .navbar_item
        .buttons style='margin-top: 12px; margin-left: 1rem;'
          - if @post.present? && @post.id.present? && can?(:update, @post)
            => link_to 'Edit Post', edit_post_path(@post),
              class: 'navbar-item button is-small is-link'

          - if current_user.admin? || current_user.editor?
            => link_to('New Post', new_post_url,
                class: 'navbar-item button is-small is-success')
    .navbar-end
      .navbar-item
        .buttons.has-addons
          - if current_user.admin?
            = link_to dashboard_path, class:'button is-link is-rounded is-small' do
              span Dashboard

app/views/application/_user_card.html.slim
div class='column
        columns
        is-4-tablet
        is-4-desktop
        is-4-widescreen
        box hero'
  = user_avatar(@post.user)
  .column.is-two-fifth style='display: flex; flex-direction: column-reverse;'
    .is-size-6
      .div
        == "<h1><strong>Author: </strong> #{strip_tags @post.user.name}</h1>"